# Generated by Django 4.2.3 on 2023-10-31 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0002_childavatar_child"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="registration_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
