# Generated by Django 4.2.3 on 2023-12-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0003_child_registration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childavatar",
            name="avatar",
            field=models.ImageField(upload_to="child_avatars/"),
        ),
    ]
