# Generated by Django 4.2.3 on 2023-11-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='current_date',
            field=models.DateField(auto_now=True),
        ),
    ]
