FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir /backend_app

WORKDIR /backend_app

COPY . .

RUN pip install -U pip && \
    pip install -r requirements.txt

CMD bash -c "python manage.py collectstatic --no-input &&\
    python manage.py migrate && \
    gunicorn -c gunicorn.conf.py chytozavrik.wsgi:app
# TODO
