version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_chytozavryk
    ports:
      - $SQL_PORT:5432
    environment:
      - POSTGRES_USER=$SQL_USER
      - POSTGRES_PASSWORD=$SQL_PASSWORD
      - POSTGRES_DB=$SQL_DATABASE
    restart: always
    networks:
      - chytozavryk

  redis:
    container_name: redis_chytozavryk
    image: redis:7.2.3
    ports:
      - $REDIS_PORT:6379
    command:
      redis-server --port $REDIS_PORT --requirepass $REDIS_PASSWORD --maxmemory 100mb
    restart: always
    networks:
      - chytozavryk

  backend_app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_app_chytozavryk
    ports:
      - $BACKEND_PORT:8000
    command: [ 'bash', 'scripts/backend_app.sh' ]
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - chytozavryk

networks:
  chytozavryk:
    driver: bridge
