# Generated by Django 4.2.3 on 2023-11-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_contact_current_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="current_date",
        ),
        migrations.AddField(
            model_name="contact",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
