# Generated by Django 4.2.3 on 2023-10-30 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="partner",
            name="name",
            field=models.CharField(default="rect", max_length=255),
            preserve_default=False,
        ),
    ]
