# Generated by Django 4.2.3 on 2023-11-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_book_is_recommended_delete_recommendationbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="childquizattempt",
            name="total_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
