# Generated by Django 4.2.3 on 2023-11-03 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0004_childquizattempt_last_attempt_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="childquizattempt",
            name="last_quiz_id",
        ),
    ]
