# Generated by Django 4.2.3 on 2023-11-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0005_remove_childquizattempt_last_quiz_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizreward",
            name="reward",
            field=models.FileField(upload_to="rewards/"),
        ),
    ]
