# Generated by Django 4.2.3 on 2023-10-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_recommended",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="RecommendationBook",
        ),
    ]
