# Generated by Django 4.2.3 on 2023-11-03 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0003_childquizattempt_total_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="childquizattempt",
            name="last_attempt_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="childquizattempt",
            name="last_quiz_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
