# Generated by Django 4.2.3 on 2024-01-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0006_alter_quizreward_reward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.FileField(upload_to="books/"),
        ),
    ]
