# Generated by Django 4.2.3 on 2023-10-30 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0002_partner_created_at_partner_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="partner",
            unique_together={("name", "link")},
        ),
    ]
