# Generated by Django 4.2.3 on 2024-01-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0003_alter_partner_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="img",
            field=models.FileField(upload_to="partners/"),
        ),
    ]
